package es.unican.ps.web;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertEquals;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class NewParkingTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver.exe");


		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;	
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void newParking() {
	    driver.get("http://localhost:8080/UCParkWeb/");
	    driver.manage().window().setSize(new Dimension(1552, 840));
	    driver.findElement(By.name("j_idt6:j_idt9")).click();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("hector@gmail.com");
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("hector");
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.linkText("Parking")).click();
	    driver.findElement(By.linkText("New parking")).click();
	    driver.findElement(By.name("j_idt6:j_idt9")).click();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("1111-AAA");
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("30");
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.cssSelector("h1")).click();
	    assertEquals("Active parking", driver.findElement(By.cssSelector("h1")).getText());
	    driver.findElement(By.linkText("Home")).click();
	    driver.findElement(By.linkText("Parking")).click();
	    driver.findElement(By.linkText("New parking")).click();
	    
	    clear();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("1111-AAA");
	    driver.findElement(By.name("j_idt6:j_idt11")).click();
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("60");
	    driver.findElement(By.cssSelector("tr:nth-child(1)")).click();
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.cssSelector("h1")).click();
	    assertEquals("New parking", driver.findElement(By.cssSelector("h1")).getText());
	    driver.findElement(By.cssSelector("tr:nth-child(1)")).click();
	    
	    clear();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("2222-BBB");
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("140");
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.cssSelector("h1")).click();
	    assertEquals("New parking", driver.findElement(By.cssSelector("h1")).getText());
	    driver.findElement(By.cssSelector("tr:nth-child(1)")).click();
	    
	    clear();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("2222-BBB");
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("-40");
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.cssSelector("h1")).click();
	    assertEquals("New parking", driver.findElement(By.cssSelector("h1")).getText());
	    clear();
	    driver.findElement(By.name("j_idt6:j_idt9")).click();
	    driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("2222-BBC");
	    driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("90");
	    driver.findElement(By.name("j_idt6:j_idt12")).click();
	    driver.findElement(By.cssSelector("h1")).click();
	    assertEquals("New parking", driver.findElement(By.cssSelector("h1")).getText());
	}

	/**
	 * Clears both fields (otherwise, text is appended instead of replaced).
	 * 
	 */
	private void clear() {
		driver.findElement(By.name("j_idt6:j_idt9")).clear();
		driver.findElement(By.name("j_idt6:j_idt11")).clear();
	}

}
